### ISSUE TITLE
K03-overly-permissive-rbac - reference k8s RBAC good practice guide

### ISSUE THREAD

**Issue by raesene** [OWASP/www-project-kubernetes-top-ten#2]
There's a newly published Kubernetes [RBAC good practice guide](https://kubernetes.io/docs/concepts/security/rbac-good-practices/) which could make a good reference for this entry in the Top 10

**Comment by jmbmxer** [comment]
good call! This has been added.
https://github.com/OWASP/www-project-kubernetes-top-ten/blob/main/2022/en/src/K03-overly-permissive-rbac.md
