### ISSUE TITLE
Is the term principle of  "least privilege" should instead of "lease privilege" ？ 

### ISSUE THREAD

**Issue by shadowedge** [OWASP/www-project-kubernetes-top-ten#20]
hello:
in [K03-overly-permissive-rbac.md](https://github.com/OWASP/www-project-kubernetes-top-ten/blob/main/2022/en/src/K03-overly-permissive-rbac.md), I find the term _principle of  **lease privilege**_ , but I can't find  it anywhere, except the term _principle of **least privilege**_ . 
So, maybe the term "least privilege" should instead of "lease privilege" , or please tell me where can  I find the reference or explaination of the term **lease privilege**?

**Comment by jmbmxer** [comment]
fixed! Good catch.
