### ISSUE TITLE
Bound service account tokens expire

### ISSUE THREAD

**Issue by eclipse612** [OWASP/www-project-kubernetes-top-ten#22]
Hi! 

In risk [#6 Broken Authentication](https://github.com/OWASP/www-project-kubernetes-top-ten/blob/main/2022/en/src/K06-broken-authentication.md), the following measure is mentioned:  

**_Don’t use Service Account tokens from outside of the cluster:_** SAs can’t be bound to groups and they never expire. Using the long-lived SA from outside of the cluster opens your cluster up to significant risk.

It seems like this information does not take the Bound Service Account Tokens improvement (available from K8s 1.22) into account, see https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/ . Service Account Tokens do actually expire nowadays.

The guidance is of course still very valid, but maybe the reasoning behind it should be updated a bit. 

Thanks!

**Comment by szh** [comment]
Thank you @eclipse612. Do you want to take a crack at updating this with a PR?
