### ISSUE TITLE
Extra "the" in index.md rendering on the landing page

### ISSUE THREAD

**Issue by scriptingxss** [OWASP/www-project-kubernetes-top-ten#24]
Heads up - The index.md has an extra "the". See https://github.com/OWASP/www-project-kubernetes-top-ten/blob/main/index.md?plain=1#L13. The readme looks fine.

**Comment by jmbmxer** [comment]
👍 done and done

**Comment by szh** [comment]
Well that was fast! I was about to create a PR for this :)
