### ISSUE TITLE
Rendering the guide markdown

### ISSUE THREAD

**Issue by RichardoC** [OWASP/www-project-kubernetes-top-ten#35]
Is there a reason the posts aren't actually rendered, and are instead just presented as markdown through the GitHub UI?

For context I was trying to add some steps (https://github.com/RichardoC/www-project-kubernetes-top-ten/tree/contributing) so I could test my PR ( #34 ) locally when I realised they aren't actually rendered. The index links to https://github.com/OWASP/www-project-kubernetes-top-ten/blob/main/2022/en/src/K05-inadequate-logging.md for example.

Thanks,

**Comment by Jeymz** [comment]
I was just wondering the same thing. It would be nice to not have to click back and forth and have a list of the items on the side or a next button.

**Comment by Jeymz** [comment]
Went ahead and did this if @jmbmxer or somebody would like to review #44
